### ISSUE TITLE
Add Auto Minimize to reduce CPU Usage 

### ISSUE THREAD

**Issue by kevinvud1** [fkingnoobgg/lolbot#4]

**Comment by noobling** [comment]
Thanks for suggestion. You could easily and quickly implement this yourself with a batch script.

**Comment by noobling** [comment]
I have had a look and the issue with this is that when you minimise some errors will not get detected so really it is a choice between stability and performance so I will close this one for now.

EDIT:
Actually I have solved this issue and you can look forward to it being added by default in next update.
