### ISSUE TITLE
Garena?

### ISSUE THREAD

**Issue by MrKser** [fkingnoobgg/lolbot#5]
Garena Server don't work
https://www.elobuddy.net/applications/core/interface/imageproxy/imageproxy.php?img=https://snag.gy/Ys87zt.jpg&key=46f4370c2b547407b57076bb89095aca0c5b52d0c3676ad83520da3289af09b5

**Comment by noobling** [comment]
Thanks I am aware of that

**Comment by noobling** [comment]
hmmm I don't plan on making garena work again because I would like it if people had the money to go and buy hesabot 
https://www.hesabot.com/
